name = "BCRSimplexGaps"
uuid = "816a52eb-2c09-4c43-9238-cfe450cf25a4"
authors = ["Robert Three <roberthree@proton.me> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.8.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
